### ISSUE TITLE
Add set_title() method to session.get_project(...)

### ISSUE THREAD

**Issue by MystPi** [CubeyTheCube/scratchclient#10]
I would love for this to be added:
```python
session.get_project(id).set_title("New Title Text")
```

Thanks! 😃 
\- NFlex23 on Scratch

**Comment by CubeyTheCube** [comment]
will do

**Comment by MystPi** [comment]
> will do

Thanks!

**Comment by Sid72020123** [comment]
I found a way to do it!

**Comment by Sid72020123** [comment]
Use `requests.put()` and the data dictionary converted to JSON along with the json headers.

**Comment by CubeyTheCube** [comment]
done

**Comment by Sid72020123** [comment]
Thank you! Remember to give me the credit :)
