### ISSUE TITLE
(New feature) Filter messages

### ISSUE THREAD

**Issue by Quantum-Codes** [CubeyTheCube/scratchclient#14]
filter by type in getting messages. (Not count. The message itself)
```python
 x = session.get_messages(all=False,limit=40,offset=40,filter="comments")
```
See the filter argument? Thats my suggestion.  The argument does exists on scratch REST API link

_How do i put a label btw?_

**Comment by Sid72020123** [comment]
In the program add '&filter=' to make it work.

**Comment by Sid72020123** [comment]
Finally! I added it: https://github.com/Sid72020123/scratchclient
Can anyone test it? Because I am not sure it will work.

**Comment by Quantum-Codes** [comment]
> Finally! I added it: https://github.com/Sid72020123/scratchclient
> Can anyone test it? Because I am not sure it will work.

How do I test? Can't run code on github

**Comment by Sid72020123** [comment]
Copy the code an run it locally or on replit.

**Comment by Quantum-Codes** [comment]
Ok lemme try

**Comment by Sid72020123** [comment]
You can also run github code on replit.

**Comment by CubeyTheCube** [comment]
ok
