### ISSUE TITLE
Having trouble installing scratchclient...

### ISSUE THREAD

**Issue by therealxouzouris** [CubeyTheCube/scratchclient#24]
(After downloading scratchclient) I type 'pip install scratchclient' into the command prompt and python but it doesn't recognize the command. What do I need to do to get it to work? (I'm a begginer)

**Comment by Quantum-Codes** [comment]
```python
import os
os.system('pip install scratchclient')
from scratchclient import ScratchSession 
session = ScratchSession(username here,password here)
```

**Comment by therealxouzouris** [comment]
> ```python
> import os
> os.system('pip install scratchclient')
> from scratchclient import ScratchSession 
> session = ScratchSession(username here,password here) #login details
> ```
> 
> If you always don't wanna install whenever u run:
> 
> ```python
> import os
> try:
>     from scratchclient import ScratchSession
> except ModuleNotFoundError:
>     os.system('pip install scratchclient')
>     from scratchclient import ScratchSession
> #login details here
> ```

Doesn't work...

**Comment by Quantum-Codes** [comment]
Idk then.. @CubeyTheCube

**Comment by therealxouzouris** [comment]
Wait, I think pip isn't pre-installed for me... I'm going to try to install it and see if it'll work then.

**Comment by Quantum-Codes** [comment]
> Wait, I think pip isn't pre-installed for me... I'm going to try to install it and see if it'll work then.

Worked?
