### ISSUE TITLE
Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by coco7nut001** [CubeyTheCube/scratchclient#26]
`  Complete output (10 lines):                                                                                             running bdist_wheel                                                                                                     running build                                                                                                           running build_py                                                                                                        creating build                                                                                                          creating build\lib.win-amd64-3.9                                                                                        creating build\lib.win-amd64-3.9\wsaccel                                                                                copying wsaccel\__init__.py -> build\lib.win-amd64-3.9\wsaccel                                                          running build_ext                                                                                                       building 'wsaccel.utf8validator' extension                                                                              error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/   `

**Comment by CubeyTheCube** [comment]
this is known, you have to install microsoft visual c++

if you don't want to, clone the repo and remove the line that imports wsaccel (https://github.com/CubeyTheCube/scratchclient/blob/main/scratchclient/CloudConnection.py#L5)
