### ISSUE TITLE
ValueError: Variable '☁ cloud0' is not in this project

### ISSUE THREAD

**Issue by StampDanFan** [CubeyTheCube/scratchclient#27]
Hi!
I've been using this module for scratch API and for the most part, it works great.
However, I've run into a bit of a problem.

I created a scratch project with 10 cloud variables:
cloud1, cloud2, cloud3, cloud4, cloud5, cloud6, cloud7, cloud8, cloud9, cloud0.
Whenever I try to access the last cloud variable created, I get this error:
```python
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/scratchclient/CloudConnection.py", line 117, in get_cloud_variable
    var = next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    cloudvars = [connection.get_cloud_variable("cloud"+str(i)) for i in range(0, 10)]
  File "main.py", line 13, in <listcomp>
    cloudvars = [connection.get_cloud_variable("cloud"+str(i)) for i in range(0, 10)]
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/scratchclient/CloudConnection.py", line 124, in get_cloud_variable
    raise ValueError(
ValueError: Variable '☁ cloud0' is not in this project
```

Additionally, I tried it with another project with 10 cloud variables, and I got the same error for the last cloud variable I created.

I was looking through the CloudConnection class and saw the property _cloudvariables.
I printed its length, and got 9, even though I made 10 cloud variables in the project.
```python
connection = session.create_cloud_connection(projectID)
print(len(connection._cloudvariables)) # 9
```

Any help would be appreciated :)

**Comment by Quantum-Codes** [comment]
Scratch cloud is weird..  sometimes cloud doesn't work.
Here is my experience: https://scratch.mit.edu/discuss/topic/506883/?page=1#post-5155478

**Comment by pikachub2005** [comment]
If the variable wasn't updated recently enough to be in the api list, then it can't get the value. Is that the issue?

**Comment by billyBob456** [comment]
I got this too just right now. Getting cloud variables doesn't work.

**Comment by silvxrcat** [comment]
Here's a screenshot of some example code from the forum post.
![image](https://user-images.githubusercontent.com/82522464/148693322-2fc72e18-58b7-4bb6-a971-7bea3476cf94.png)
It seems like the emoji is the problem here. Try removing it.

**Comment by CubeyTheCube** [comment]
Scratch takes a while to update its variables, I doubt you still have this problem a year later anyway.
