### ISSUE TITLE
View Studio Comments

### ISSUE THREAD

**Issue by ajsya** [CubeyTheCube/scratchclient#28]
Not sure if this is possible, but It would be cool if you could view studio comments like you can already do with projects.

**Comment by Quantum-Codes** [comment]
It is possible

**Comment by ajsya** [comment]
How would someone accomplish this?

**Comment by Sid72020123** [comment]
It is possible! I have made a same library like this and I have also added get studio comments and much more!

**Comment by Sid72020123** [comment]
There is an Scratch API to make it work!

**Comment by ajsya** [comment]
Thanks for letting me know, I'll check it out.
