### ISSUE TITLE
Get REAL message count

### ISSUE THREAD

**Issue by Naleksuh** [CubeyTheCube/scratchclient#29]
Please use https://scratch.mit.edu/messages/ajax/get-message-count/ for retrieving a user's own message count, because the scratch-api version returns an incorrect message count more often than not (yet another reason why scratch-api is terrible and needs to be stopped).

As for finding someone else's message count, there is no reason why someone should need to do that in the first place. Especially not with a client, since that information isn't available through normal usage of the Scratch website

**Comment by pikachub2005** [comment]
The ST chose for it to be public (unlike someone's actual messages). What could someone do with the amount anyway?

**Comment by Naleksuh** [comment]
That page also just returns the count. However, its count is much more accurate than the terrible scratch-api count

**Comment by CubeyTheCube** [comment]
the scratch team doesn't really want people getting message counts anyway, so I'll just leave it be
