### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by ajsya** [CubeyTheCube/scratchclient#30]
I got this error trying to install using pip. Please advice.

`    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wy/6_2ngzh15fxbt5w1c_r5kbj80000gq/T/pip-install-90s79uot/wsaccel_9592b2a1c9b5498aaf0ca889b7483db0/setup.py'"'"'; __file__='"'"'/private/var/folders/wy/6_2ngzh15fxbt5w1c_r5kbj80000gq/T/pip-install-90s79uot/wsaccel_9592b2a1c9b5498aaf0ca889b7483db0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/wy/6_2ngzh15fxbt5w1c_r5kbj80000gq/T/pip-record-nzf2b09x/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/wsaccel
         cwd: /private/var/folders/wy/6_2ngzh15fxbt5w1c_r5kbj80000gq/T/pip-install-90s79uot/wsaccel_9592b2a1c9b5498aaf0ca889b7483db0/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/wsaccel
    copying wsaccel/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/wsaccel
    running build_ext
    building 'wsaccel.utf8validator' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/wsaccel
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c wsaccel/utf8validator.c -o build/temp.macosx-10.9-x86_64-3.8/wsaccel/utf8validator.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wy/6_2ngzh15fxbt5w1c_r5kbj80000gq/T/pip-install-90s79uot/wsaccel_9592b2a1c9b5498aaf0ca889b7483db0/setup.py'"'"'; __file__='"'"'/private/var/folders/wy/6_2ngzh15fxbt5w1c_r5kbj80000gq/T/pip-install-90s79uot/wsaccel_9592b2a1c9b5498aaf0ca889b7483db0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/wy/6_2ngzh15fxbt5w1c_r5kbj80000gq/T/pip-record-nzf2b09x/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/wsaccel Check the logs for full command output.`

**Comment by CubeyTheCube** [comment]
> What do the logs say? I think I had the same error as you. What I had to do is to install Visual C++ (MSVC), and then include cl.exe in my path. Next I got an error about io.h, which I haven't gotten past. What I think I'm going to do is use the parts of the source code that I need, rather than installing the library.

This error probably won't occur anymore, but I'm not sure.
