### ISSUE TITLE
Can't love project

### ISSUE THREAD

**Issue by pikachub2005** [CubeyTheCube/scratchclient#33]
I get 
```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Service Unavailable</title>
  </head>
  <body>
    <h1>Error 503 Service Unavailable</h1>
    <p>Service Unavailable</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-pwk4953-PWK 1632708762 3862752377</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```
I'm guessing this is a scratch thing but idk

**Comment by pikachub2005** [comment]
nvm just won't work bc I'm banned ;-;

**Comment by Quantum-Codes** [comment]
> nvm just won't work bc I'm banned ;-;

You too?? Why

**Comment by pikachub2005** [comment]
> > nvm just won't work bc I'm banned ;-;
> 
> You too?? Why

I posted a shortened url on a friend's profile and it got reported. I'm working on [this](https://scratchplus.am4.uk ) because of it. (Look [here](https://replit.com/@PikachuB2005/ScratchPlus?v=1 ) if you don't trust it)

**Comment by pikachub2005** [comment]
> > nvm just won't work bc I'm banned ;-;
> 
> You too?? Why

For some reason replit gave me a "education account" so I can't reply to your comment on the repl. To answer your question, it can be a workaround for some things, but stuff like loving/ favoriting projects doesn't work for banned users. It's still a work in progress so expect a lot of issues.  Your password is NOT saved, it's only used to get your tokens, which are saved in cookies. The endpoint /secret only exists because I was bored, and you must be logged in to use it.

**Comment by Quantum-Codes** [comment]
> > > nvm just won't work bc I'm banned ;-;
> > 
> > 
> > You too?? Why
> 
> For some reason replit gave me a "education account" so I can't reply to your comment on the repl. To answer your question, it can be a workaround for some things, but stuff like loving/ favoriting projects doesn't work for banned users. It's still a work in progress so expect a lot of issues. Your password is NOT saved, it's only used to get your tokens, which are saved in cookies. The endpoint /secret only exists because I was bored, and you must be logged in to use it.

Ah ok...
