### ISSUE TITLE
Where is the setup.py?

### ISSUE THREAD

**Issue by ninjamar** [CubeyTheCube/scratchclient#40]
Where is the setup.py?

**Comment by Quantum-Codes** [comment]
It isn't there. He doesn't upload it to github

**Comment by ninjamar** [comment]
He should if we want to build the package from source.

**Comment by Quantum-Codes** [comment]
I think he builds locally. (I too don't build from github lol)

**Comment by ninjamar** [comment]
Some people build from source though

**Comment by Quantum-Codes** [comment]
Ok

**Comment by themysticsavages** [comment]
I agree, a setup py file would be nice since it could install packages like pymitter for you. Also, why is numpy and wsaccel in the code if it's not needed?

**Comment by CubeyTheCube** [comment]
Ok
