### ISSUE TITLE
Cloud Connection Hangs

### ISSUE THREAD

**Issue by MystiK791** [CubeyTheCube/scratchclient#43]
When I attempt to connect to a cloud variable in [this project](https://scratch.mit.edu/projects/639147574/), it hangs. It doesn't crash or break, nor does it throw any errors, it just becomes completely unresponsive. I'm using the code found at [this repo](https://github.com/Techguy791/Am-I-Online) to attempt to interface with it. During testing (using [this project](https://scratch.mit.edu/projects/638632131/)), it interfaced with the project just fine. At the time, I was using my main account to control the python code and my alt to sign into Scratch. What might be causing this?

**Comment by Quantum-Codes** [comment]
> Create an alternate/dummy account. Due to what's presumably a quirk with the Scratch API, you cannot use the same account you remixed the project with to interface with the cloud variables

Maybe try logging in with main account and running code with your alt?

**Comment by thegamebegins25** [comment]
I have the same problem!

**Comment by Quantum-Codes** [comment]
> I have the same problem!

Send the code (make sure to not give password)

**Comment by thegamebegins25** [comment]
`session = scratch.ScratchSession(name, pword)`
`connection = session.create_cloud_connection(id)`
Will hang on the second line for about 10 minutes then give a blank connection (no cloud variables to interact with)(this only happens on certain projects)

**Comment by Techguy791** [comment]
Like I said, it worked on an earlier version of the project, using an identical variable setup.

**Comment by CubeyTheCube** [comment]
A lot of the cloud code is different now so if there's a problem it'll probably be different now.

**Comment by thegamebegins25** [comment]
Thanks for helping me!
