### ISSUE TITLE
create_cloud_session does not work

### ISSUE THREAD

**Issue by xAspirus** [CubeyTheCube/scratchclient#47]
```py
session.create_cloud_connection()
```
Does not work
it stays stuck

**Comment by Quantum-Codes** [comment]
Might be because `self` doesn't come before the ID here?
https://github.com/CubeyTheCube/scratchclient/blob/841cfafa04d4fa4d2225fdc2461f687a96308058/scratchclient/ScratchSession.py#L140

**Comment by xAspirus** [comment]
https://github.com/CubeyTheCube/scratchclient/blob/841cfafa04d4fa4d2225fdc2461f687a96308058/scratchclient/CloudConnection.py#L22
the self there is the client instance

**Comment by CubeyTheCube** [comment]
A lot of the cloud-related code is different now, so I'm not sure how relevant this still is.
