### ISSUE TITLE
Cannot get studio.

### ISSUE THREAD

**Issue by BadPythonCoder** [CubeyTheCube/scratchclient#50]
I tried to get a studio but it returned this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/runner/Broadcasting/venv/lib/python3.8/site-packages/scratchclient/ScratchSession.py", line 82, in get_studio
    return self._to_studio(
  File "/home/runner/Broadcasting/venv/lib/python3.8/site-packages/scratchclient/ScratchSession.py", line 60, in _to_studio
    return Studio(data, self)
  File "/home/runner/Broadcasting/venv/lib/python3.8/site-packages/scratchclient/Studio.py", line 12, in __init__
    self.owner = data["owner"]
KeyError: 'owner'
This was my code:
import scratchclient

session = scratchclient.ScratchSession(USER, PASS)
studio = session.get_studio(ID)
[insert the other code here]

Could somebody help? That would be very appreciated.

**Comment by Quantum-Codes** [comment]
This isn't your fault.. it's a problem in the package

**Comment by BadPythonCoder** [comment]
> Why don't you try manually requesting to the API link? Or use another package? I can help you to do both

I tried some others packages and they didn't work sadly. Maybe i chose the wrong ones.
I think i will manually request to the API. What is the URI and required parameters?
Thanks in advance.

**Comment by Quantum-Codes** [comment]
> > Why don't you try manually requesting to the API link? Or use another package? I can help you to do both
> 
> I tried some others packages and they didn't work sadly. Maybe i chose the wrong ones. I think i will manually request to the API. What is the URI and required parameters? (i don't know much about the scratch API lol) Thanks in advance.

Um I think I shouldn't say about other packages in this repo lol

**Comment by BadPythonCoder** [comment]
I have found the URI i needed. Still thanks for proposing the idea of making the request myself. Why didn't i think of that lol. Anyway, it works now.
