### ISSUE TITLE
KeyError: 'set-cookie'

### ISSUE THREAD

**Issue by The-Cloud-Dev** [CubeyTheCube/scratchclient#8]
This is my code:
` from scratchclient import ScratchSession
session = ScratchSession('TheCloudDev','passwordhere') `
And the traceback:
 File "C:\Users\**********************\test2.py", line 3, in <module>
    session = ScratchSession('TheCloudDev','Password')
  File "C:\Users\*********************\Python\Python39\lib\site-packages\scratchclient\ScratchSession.py", line 19, in __init__
    self.login(password)
  File "C:\Users\**********\Programs\Python\Python39\lib\site-packages\scratchclient\ScratchSession.py", line 36, in login
    self.session_id = re.search('"(.*)"', request.headers["Set-Cookie"]).group()
  File "C:\Users\***********\Programs\Python\Python39\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
It may be a problem with Scratch, My module [scratch2py](https://github.com/The-Cloud-Dev/scratch2py/) doesn't work either and returns the same error

**Comment by AmazingMech2418** [comment]
Same with (https://npmjs.com/package/scratchcloud)[ScratchCloud]...

**Comment by CubeyTheCube** [comment]
> Same with [ScratchCloud](https://npmjs.com/package/scratchcloud)...

Yep, scratch broke something. I'm going to try to find the root cause.

**Comment by CubeyTheCube** [comment]
@AmazingMech2418 I think Scratch requires something else in the Cookie that they didn't require before... have you identified how this can be fixed?

**Comment by AmazingMech2418** [comment]
@CubeyTheCube I'm working on it right now. The issue is that the CSRF tokens aren't authenticating...

**Comment by CubeyTheCube** [comment]
> @CubeyTheCube I'm working on it right now. The issue is that the CSRF tokens aren't authenticating...

@AmazingMech2418 For me it just says "Something went wrong", even when I completely duplicated my actual cookie on scratch.mit.edu

**Comment by AmazingMech2418** [comment]
@CubeyTheCube Yeah, I'm getting the same thing too.

**Comment by AmazingMech2418** [comment]
@CubeyTheCube You have to add a bunch of headers too. All of the `sec-...` headers...

**Comment by AmazingMech2418** [comment]
@CubeyTheCube It's probably to keep people from botting it...

**Comment by CubeyTheCube** [comment]
@AmazingMech2418 Figured it out, it's only the user agent that's needed. (and it's only for the login afaik). Will fix now

**Comment by AmazingMech2418** [comment]
> @AmazingMech2418 Figured it out, it's only the user agent that's needed. (and it's only for the login afaik). Will fix now

The other headers wouldn't hurt to add though... In case the ST does try another thing...

**Comment by CubeyTheCube** [comment]
> > @AmazingMech2418 Figured it out, it's only the user agent that's needed. (and it's only for the login afaik). Will fix now
> 
> The other headers wouldn't hurt to add though... In case the ST does try another thing...

I don't want to confuse people reading the code (there's a surprising amount of people doing that for some reason) so I'll leave it be for now.
